### PR TITLE
Wheel underlay

### PR DESCRIPTION
**Pull request by ScaryG**
For your consideration!

I've added support for wheel underlays that go between the playfield and the wheel images, with a configurable height offset in the options menu. 

Please take a look and see what you think. Cheers!

-- Dave

### CODE REVIEW

**Comment by mkalkbrenner** [comment]
+1 for this feauture :-)

**Comment by mjrgh** [comment]
Just FYI - if you want to remove the Shutdown command (or any other commands) from one of the menus, you can do this with Javascript.  No need for adding Yet Another Option for this sort of customization.  See **To delete an item in a system menu** in **Javascript scripting > Events > Event Types > MenuEvent** in the help.

**Comment by mjrgh** [comment]
I'm curious - what's the use case for the offset height setting?

**Comment by mjrgh** [comment]
I've implemented similar functionality now in the base branch - see commit 4e5ad87146a75b4dc94bdcd3953a832c77187937.

**Pull request closed without merging**
